# Generated by Django 2.2.3 on 2019-08-18 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter author pen name', max_length=30)),
                ('first_name', models.CharField(help_text='enter author first name', max_length=30)),
                ('last_name', models.CharField(help_text='enter author last name , max 100 chars.', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_deth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(help_text='ISBN for book max 13 chars.', max_length=13, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(help_text='books title', max_length=100)),
                ('summary', models.CharField(help_text='book summary text.', max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter book genre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter book language', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Instance',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='GUID')),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('o', 'on loane'), ('a', 'available'), ('m', 'maintenance')], default='a', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
    ]
