# Generated by Django 2.2.3 on 2019-08-20 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20190818_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_instance',
            options={'verbose_name': 'Book Instance'},
        ),
        migrations.AddField(
            model_name='book_instance',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
